### ISSUE TITLE
MS01 - Repensar a utilização de Project, Milestone e Labels

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/salic-br#139]
Eu como _Product Owner_ quero poder participar melhor (assumir os papeis) em todos os rituais do Scrum, principalmente no _Sprint Planning_.

Remover a utilização da estrutura de Project tanto para agrupar Issues relacionadas (_Epic User Story_) como também para definir a Sprint. (Continuação da engenharia reversa...).

* As *Sprint* devem ser registradas como _Milestone_
* Utilizar o conceito de _Epic User Story_ para agrupar _User Stories_ relacionadas. Ambos são Issues com nomenclaturas específicas
* Definir novas *Labels* mais estruturantes. ex.: https://github.com/fga-gpp-mds/2017.2-QueroCultura/issues

**Comment by vinnyfs89** [comment]
Executamos os itens solicitados.
- [x] As Sprint devem ser registradas como Milestone
- [x] Utilizar o conceito de Epic User Story para agrupar User Stories relacionadas. Ambos são Issues com nomenclaturas específicas
- [x] Definir novas Labels mais estruturantes. ex.: https://github.com/fga-gpp-mds/2017.2-QueroCultura/issues
